export const DOCUMENT_TYPE_LABELS = {
  incorporation_certificate: "Incorporation certificate",
  articles_of_association_or_bylaws: "Articles of association",
  continuation_certificate: "Continuation certificate",
  discontinuance_certificate: "Discontinuance certificate",
  dissolution_certificate: "Dissolution certificate",
  registry_extract_certificate: "Registry extract certificate",
  registry_filing: "Registry filing",
  administrative_certificate: "Administrative certificate",
  good_standing_certificate: "Good standing certificate",
  board_resolution: "Board resolution",
  board_meeting_minutes: "Board meeting minutes",
  shareholder_resolution: "Shareholder resolution",
  shareholder_meeting_minutes: "Shareholder meeting minutes",
  director_appointment: "Director appointment",
  director_resignation: "Director resignation",
  director_resolution: "Director resolution",
  share_certificate: "Share certificate",
  share_register: "Share register",
  share_transfer_agreement: "Share transfer agreement",
  share_contribution_agreement: "Share contribution agreement",
  power_of_attorney: "Power of attorney",
  proxy: "Proxy",
  intercompany_or_other_agreement: "Agreement",
  banking_payment_or_credit_record: "Banking or payment record",
  annual_accounts_financial_statements: "Annual accounts",
  tax_document: "Tax document",
  legal_declaration: "Legal declaration",
  legal_opinion: "Legal opinion",
  corporate_data_sheet: "Corporate data sheet",
  registry_extract: "Registry extract",
  correspondence: "Correspondence",
  other: "Other document"
};
